# Generated by Django 5.1 on 2024-08-10 11:38

import django.db.models.deletion
import graphql_api.utils.commons
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('uuid', models.CharField(default=graphql_api.utils.commons.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('uuid', models.CharField(default=graphql_api.utils.commons.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uuid', models.CharField(default=graphql_api.utils.commons.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('kind', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('uuid', models.CharField(default=graphql_api.utils.commons.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('uuid', models.CharField(default=graphql_api.utils.commons.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.chief')),
            ],
        ),
    ]
